# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
cover: /img/teaser.png
logo: /img/logo.png
signup_form: https://goo.gl/forms/PGwzoWr7tdQqqR3w1

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: https://twitter.com/neworleansdsa
facebook: https://facebook.com/neworleansdsa
google_plus:
fb_admins:
fb_app_id:
